default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("DB_USERNAME", "") %>
  password: <%= ENV.fetch("DB_PASSWORD", "") %>
  host: <%= ENV.fetch("DB_HOST", "") %>
  port: <%= ENV.fetch("DB_PORT", "") %>

development:
  <<: *default
  database: rails_playground_development

test:
  <<: *default
  database: rails_playground_test

production:
  <<: *default
  database: rails_playground_production
  url: <%= ENV['DATABASE_URL'] %>
