name: CI

on: [push, pull_request]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Ruby & gems
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.0.2
        bundler-cache: true
        cache-version: 1

    - name: Run RuboCop
      run: bundle exec rubocop --parallel

    - name: Run Tests
      run: bundle exec rspec
